In [2]:
import numpy as np

In [48]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [3]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim


(1, 2, 3)

In [12]:
# To find what type are:
a1.dtype,a2.dtype,a3.dtype


(dtype('int32'), dtype('float64'), dtype('int32'))

In [18]:
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays!

In [20]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype


dtype('int32')

In [23]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
ones.dtype


dtype('float64')

In [28]:
type(ones)

numpy.ndarray

In [30]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [33]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[3, 8, 1, 7, 6],
       [4, 5, 2, 1, 9],
       [0, 7, 4, 2, 5]])

In [34]:
random_array.size

15

In [35]:
random_array.shape


(3, 5)

In [36]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.0561978 , 0.72378383, 0.72458337],
       [0.70367788, 0.66589499, 0.26096683],
       [0.37023881, 0.131217  , 0.67565929],
       [0.66319123, 0.23376212, 0.69304272],
       [0.68245428, 0.72494892, 0.97435982]])

In [37]:
random_array_2.shape


(5, 3)

In [38]:
random_array_3=np.random.rand(5,3)
random_array_3


array([[0.37231494, 0.28961633, 0.39991408],
       [0.4498131 , 0.722135  , 0.26461695],
       [0.09869022, 0.42526034, 0.09438205],
       [0.4881955 , 0.32413546, 0.50944686],
       [0.2660045 , 0.07764808, 0.88838766]])

In [41]:
np.random.seed(seed=99999)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [42]:
np.random.seed(7)
random_array_5=np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [43]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [44]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3. Viewing arrays and matrices

In [50]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [51]:
a1

array([1, 2, 3])

In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a1[0]

1

In [56]:
a2[0]

array([1. , 2. , 3.3])

In [57]:
a2.shape

(2, 3)

In [58]:
a3.shape

(2, 3, 3)

In [59]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [61]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [62]:
# Creative random arrays
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [63]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [64]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

In [65]:
a4[:, :, :, :3]

array([[[[6, 7, 7],
         [0, 7, 7],
         [5, 4, 3],
         [1, 3, 4]],

        [[9, 5, 9],
         [3, 2, 2],
         [3, 0, 9],
         [4, 5, 3]],

        [[8, 6, 7],
         [3, 8, 6],
         [6, 5, 7],
         [4, 4, 9]]],


       [[[6, 2, 6],
         [4, 1, 6],
         [1, 6, 9],
         [5, 9, 7]],

        [[9, 6, 8],
         [5, 8, 3],
         [9, 4, 7],
         [6, 2, 0]],

        [[0, 5, 7],
         [4, 9, 0],
         [7, 6, 2],
         [5, 1, 0]]]])

In [66]:
a4[:1, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]]])

## 4. Manipulating & comparing arrays


In [67]:
a1

array([1, 2, 3])

In [68]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [69]:
a1 + ones

array([2., 3., 4.])

In [70]:
# 
a1 - ones

array([0., 1., 2.])

In [71]:
a1 * ones

array([1., 2., 3.])

In [72]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [73]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [75]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [76]:
# How can you reshape a2 to be compatible with a3? 
# Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [77]:
# Solution
a1 / ones

array([1., 2., 3.])

In [78]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [79]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [80]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [81]:
# power to 2
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [83]:
# square the a2
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [84]:
a1 + ones

array([2., 3., 4.])

In [85]:
np.add(a1, ones)

array([2., 3., 4.])

In [86]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [87]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [88]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## Aggregation 
Aggregation = performing the same operation on a number of things

In [89]:
listy_list= [1,2,3]

In [90]:
type(listy_list)

list

In [91]:
sum(listy_list)

6

In [93]:
np.sum(a1)

6

Use Python's methods (sum()) on Python datatypes and use NumPy's methods on NumPy arrays (np.sum()).

In [95]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [96]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [97]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

18.3 ms ± 460 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
50.7 µs ± 1.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [98]:
18300 / 50.7 # faster from Python

360.94674556213016

In [99]:
np.max(a2)

6.5

In [101]:
np.max(a2)

6.5

In [102]:
np.mean(a2)

3.6333333333333333

In [100]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)


1.8226964152656422

In [103]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [104]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

In [105]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])